# ---------- Development Stage ----------
FROM ghcr.io/puppeteer/puppeteer:latest AS dev
WORKDIR /app
USER root
COPY package*.json ./
RUN npm install
RUN npx puppeteer browsers install chrome
COPY . .
# USER pptruser
CMD ["npm", "run", "dev"]

# ---------- Build Stage ----------
FROM ghcr.io/puppeteer/puppeteer:latest AS build
WORKDIR /app
USER root
COPY package*.json ./
RUN npm ci
RUN npx puppeteer browsers install chrome
COPY . .
# USER pptruser
RUN npm run build

# ---------- Production Stage ----------
FROM ghcr.io/puppeteer/puppeteer:latest AS prod
WORKDIR /app
USER root
COPY package*.json ./
RUN npm ci --omit=dev
RUN npx puppeteer browsers install chrome
COPY --from=build /app/dist ./dist
# USER pptruser
CMD ["npm", "run", "start"]
# # ---------- Development Stage ----------
# FROM node:22.16.0-alpine AS dev
# WORKDIR /app
# COPY package*.json ./
# RUN npm install
# COPY . .
# CMD ["npm", "run", "dev"]

# # ---------- Build Stage ----------
# FROM node:22.16.0-alpine AS build
# WORKDIR /app
# COPY package*.json ./
# RUN npm ci
# COPY . .
# RUN npm run build

# # ---------- Production Stage ----------
# FROM node:22.16.0-alpine AS prod
# WORKDIR /app
# COPY package*.json ./
# RUN npm ci --omit=dev
# COPY --from=build /app/dist ./dist
# CMD ["npm", "run", "start"]

    