version: '3.8'

services:
  scraper:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
    ports:
      - "4002:4002"
    environment:
      - NODE_ENV=dev
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:7.0
    ports:
      - "6380:6379"